package com.example.user_management_system.component.formatter;
import org.springframework.stereotype.Component;

//implementation for long messages
@Component
public class LongMessageFormatter implements MessageFormatter {

    @Override
    public String formatMessage() {
        System.out.println("Long formatter used");
        return "This is a long detailed message generated by the system.";
    }

    @Override
    public MessageType getType() {
        return MessageType.LONG;
    }
}