[pytest]

# Directory containing tests
testpaths = test

# Files that pytest should recognize as test files
python_files = test_*.py

# Functions recognized as test cases
python_functions = test_*

# test classes
python_classes = Test*

# Async support
asyncio_mode = auto