spring.application.name=vehicle-rental-system

#spring datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rapidrental_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=false

# logging
logging.level.com.training.vehiclerentalsystem=DEBUG
logging.level.org.springframework.web=DEBUG
server.port=8080

# Default Admin Configuration
app.admin.name=System Admin
app.admin.email=admin@rapidrental.com
app.admin.password=admin123
app.admin.phone=1234554321
app.admin.address=System Address

